export const WINNER_VALUE = "WINNER_VALUE";
export const GAME_LOCKED_VALUE = "GAME_LOCKED_VALUE";
export const GAME_ENDED_VALUE = "GAME_ENDED_VALUE";
export const TOTAL_MOVES_VALUE = "TOTAL_MOVES_VALUE";